name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    branches:
      - master

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          echo "matrix=$(nix eval --json '.#githubActions.matrix')" >> "$GITHUB_OUTPUT"

  build:
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: cachix/cachix-action@v14
        with:
          name: emacs-ci
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix build -L ".#githubActions.checks.${{matrix.system}}.${{ matrix.attr }}"
      - name: Test if package.el works inside Emacs
        run: cd tests && HOME=$(pwd) nix run "..#githubActions.checks.${{matrix.system}}.${{ matrix.attr }}" -- -Q --batch \
               --eval "(setq debug-on-error t)" --load init.el
