name: Update nixpkgs snapshot

on:
  schedule:
    - cron: "00 9 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Update snapshot commit
      run: 'nix flake lock --update-input nixpkgs'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: 'Update nixpkgs snapshot'
        body: ''
        commit-message: 'Update nixpkgs snapshot'
        branch: nixpkgs-snapshot-update
        branch-suffix: timestamp
        delete-branch: true
        add-paths: flake.lock
