name: Update snapshots

on:
  schedule:
    - cron: "15 9 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Update HEAD snapshot commit
      run: 'nix-shell -p niv --run "niv update emacs-snapshot"'
    - name: Update release snapshot commit
      run: 'nix-shell -p niv --run "niv update emacs-release-snapshot"'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: 'Update snapshots'
        body: ''
        commit-message: 'Update snapshots'
        branch: snapshot-update
        branch-suffix: timestamp
        delete-branch: true
        add-paths: nix/sources.*
